channels:
  - conda-forge
  - nodefaults
dependencies:
  - cf-python
  - cf-plot
  - xarray
  - pandas
  - cftime
  - matplotlib
  - cartopy
  - tqdm
  - h5py
  - fsspec
  - numpy
  - requests
  - aiohttp
